Raudius/files_scripts

docs/Functions.md
lib/Interpreter/FunctionProvider.php
lib/Interpreter/Functions/Files/Copy_File.php
lib/Interpreter/Functions/Files/Exists.php
lib/Interpreter/Functions/Files/Exists_Unsafe.php
lib/Interpreter/Functions/Files/File_Copy.php
lib/Interpreter/Functions/Files/File_Copy_Unsafe.php
lib/Interpreter/Functions/Files/File_Move.php
lib/Interpreter/Functions/Files/File_Move_Unsafe.php
lib/Interpreter/Functions/Files/Full_Path.php
lib/Interpreter/Functions/Files/Get_Parent.php
lib/Interpreter/Functions/Files/Home.php
lib/Interpreter/Functions/Files/Root.php
lib/Interpreter/RegistrableFunction.php

Addresses: #9 
This PR makes some changes to the `Files` functions:
Additions:  
* `file_copy_unsafe`: allows files to be copied to any path from the server root.
* `file_move_unsafe`: allows files to be moved to any path from the server root.
* `exists_unsafe`: allows to check if a file exists from any path from the server root
Changes: (deprecated functions are not yet removed)  
* `root()` is renamed to `home()` (root may be used later on to fetch the server root)
* `copy_file` is renamed to `file_copy` for consitency with other functions

Files functions update

---

appinfo/routes.php
docs/Admin.md
lib/Controller/ScriptController.php
lib/Controller/ScriptInputController.php
lib/Db/ScriptInput.php
lib/Interpreter/Context.php
lib/Interpreter/Functions/Input/Get_Input.php
lib/Migration/Version020100Date20221126.php
src/api/script.ts
src/components/ScriptEdit.vue
src/components/ScriptEdit/EditInputDetails.vue
src/components/ScriptEdit/EditInputs.vue
src/components/ScriptSelect/ScriptInputComponent.vue
src/components/generic/MultiInput.vue
src/types/script.ts
src/views/ScriptSelect.vue
tests/unit/Lua/InputTest.php
tests/unit/Lua/LuaTestCase.php
tests/unit/TestFunctionProvider.php

Resolves: https://github.com/Raudius/files_scripts/issues/13
Allows administrators to determine the type of the user input (text, checkbox, multiselect, file-pick). Allowing for more restrictive user inputs.
**Administration**
**Action select**

Implement different script-input types

---

lib/AppInfo/Application.php
lib/Controller/SettingsController.php
lib/Listener/LoadAdditionalListener.php
lib/Settings/AdminSettings.php
src/files.ts
src/views/ScriptSelect.vue
src/views/Settings.vue

This provide configuration option `Action in menu`, which causes that enabled script actions are directly in menu, not hiden under `More actions` item.

Actions can be directly in menu

---

src/files.ts
src/views/ScriptSelect.vue
src/views/Settings.vue

Follow-up to https://github.com/Raudius/files_scripts/pull/39
Removes console logging and also enables direct action registration on multiselect options.

Enable multi-select direct actions registration.

---

lib/Interpreter/Functions/Files/Meta_Data.php

Addresses https://github.com/Raudius/files_scripts/issues/30
Adds additional path information to the `meta_data` function:
- `storage_path`: is the path relative to the file's storage root. Storages can be: a mounted external storage (S3, SFTP, etc), a federated folder, the default data folder..
- `local_path`: is a path to a local version of the file. If the file is on an external storage this path may not be the permanent location of the file.

Add path info to `meta_data()` function

---

lib/Interpreter/Functions/Nextcloud/Tag_File_Unassign.php

Allow `tag_file_unassign` to work on folders

Fix tag_file_unassign for folders

---

lib/Controller/ScriptController.php
lib/Interpreter/Context.php
lib/Interpreter/FunctionProvider.php
lib/Interpreter/Functions/Error/Abort.php
lib/Interpreter/Functions/Error/Add_Message.php
lib/Interpreter/Functions/Error/Clear_Messages.php
src/types/Messages.ts
src/views/ScriptSelect.vue

Add ability to return custom messages to the user (beyond the abort message).
- Messages are queued and shown in order to the user with `add_message`
- Message queue can be cleared with `clear_messages`
Messages can be given a type, which affects the toast colour:
- `"info"`
- `"error"`
- `"warning"`
- `"success"`

Adds custom messages

---

CHANGELOG.md
appinfo/info.xml
package-lock.json
package.json

- Nextcloud 26 support
- Custom messages with `add_message` and `clear_messages`
- Limit actions to certain user-groups
- Added `include` function to Scripting API
- Fix example scripts not getting inputs
- Fix incomplete log messages
- Fixed occ commands not correctly parsing input
- Fixed multi-select input not allowing selection
- Fixed file-pick input default and start-browse location
- `tag_file_unassign` now works on folders
- `file_copy`/`file_move` now work on folders
- Fixed `meta_data` crashing scripts on externally mounted folders
- Updated multi-select Vue component

Bump version 2.2.0

---

lib/AppInfo/Application.php
lib/Controller/ScriptController.php
lib/Controller/ScriptInputController.php
lib/Db/Script.php
lib/Interpreter/Context.php
lib/Interpreter/ContextFactory.php
lib/Interpreter/RegistrableFunction.php
lib/Listener/ShareLinkAccessedListener.php
lib/Migration/Version030000Date20230423.php
lib/Service/PermissionService.php
src/api/script.ts
src/components/ScriptEdit.vue
src/files.ts
src/types/script.ts
src/views/ScriptSelect.vue

Resolves #31 
Adds an option to make scripts available to public shares. This only works for folder shares, and the shared folder is set as the `root()` directory for the script.

Scripts on public shares

---

.github/workflows/behat-sqlite.yml
lib/Interpreter/FunctionProvider.php
lib/Interpreter/Functions/Files/File_Delete_Unsafe.php
lib/Interpreter/Functions/Files/File_Move.php
lib/Interpreter/Functions/Files/File_Move_Unsafe.php
lib/Interpreter/Functions/Files/UnsafeViewOperationTrait.php
tests/integration/features/fixtures/test_files.lua

Addresses: https://github.com/Raudius/files_scripts/issues/103
In this PR:
- Fixes `file_move_unsafe` function which was broken by upstream changes (in-detail explanation in code-comments)
- Adds `file_delete_unsafe` function to also facilitate integration test
- Adds integration tests for "unsafe' functions

Fix file_move_unsafe, adds file_delete_unsafe

---

appinfo/info.xml
lib/Command/ExportScripts.php
lib/Command/ImportScripts.php
lib/Db/Script.php
lib/Db/ScriptInput.php
lib/Db/ScriptMapper.php
lib/Middleware/DefaultScriptsMiddleware.php
lib/Middleware/examples.json
lib/Service/ScriptService.php
lib/Service/ScriptValidationException.php

Relates to: https://github.com/Raudius/files_scripts/issues/108
This PR adds the ability to import and export JSON-serialized scripts using occ comands.
**Usage example:**
```bash
occ files_scripts:export > scripts.json
occ files_scripts:import < scripts.json
```

Add import and export script comands

---

.github/workflows/behat-sqlite.yml
lib/Interpreter/FunctionProvider.php
lib/Interpreter/Functions/Nextcloud/EventSerializerTrait.php
lib/Interpreter/Functions/Nextcloud/Get_Activity.php
tests/integration/features/fixtures/test_base.lua
tests/integration/features/fixtures/test_nextcloud.lua

Solves: https://github.com/Raudius/files_scripts/issues/109
This PR adds the ability to fetch activity data from Nextcloud objects via the `get_activity` function.
Currently it is only possible to get activity events from File objects. If/when calendar/task integration is implemented, activity data could also be fetched from `Task` and `CalendarEvent` objects.

Add `get_activity`function to API

---

lib/Interpreter/Functions/Files/File_Delete.php

Addresses: https://github.com/Raudius/files_scripts/issues/114
Adds an argument to `file_delete` to allow permanent deletion of the file, this argument prevents the file from being sent to the trash-bin.
```lua
file = get_input_files()[1]
succeed_if_not_exists = true
delete_permanently = true
file_delete(file, succeed_if_not_exists, delete_permanently)

Add ability to delete file permanently bypassing the trashbin

---

CHANGELOG.md
appinfo/info.xml
docs/Functions.md
package.json

This is the last feature release for Nextcloud 27. Future releases will only support Nextcloud 28+. 
This is due to significant changes to the Files app, which would complicate maintaining backwards-compatible integration.
- Adds parameter to `file_delete` which allows bypassing trash-bin.
- Adds `get_activity` function to get an array of the activity events for a file.
- Adds `file_delete_unsafe` for deleting files from other users.
- Adds ability to export script collections via `occ files_scripts:export`.
- Adds ability to import script collections via `occ files_scripts:import`.
- Fixed `file_move_unsafe` function on Nextcloud 27.
- Fixed missing database default value on script input `options` column.

Release 3.1.0

---

lib/Controller/ScriptController.php
lib/Db/Script.php
lib/Middleware/examples.json
lib/Migration/Version031000Date20231211.php
src/components/ScriptEdit.vue
src/files.ts
src/store/scripts.ts
src/types/script.ts
src/views/ScriptSelect.vue
tests/integration/features/bootstrap/FeatureContext.php

Addresses: https://github.com/Raudius/files_scripts/issues/113
This PR allows restricting file actions by file types, this replaces the old mimetype limitation.
You can now select multiple MIME-types and extensions as seen below:

Restrict file action by file types (mime or extension)

---

composer.json
composer.lock
lib/Interpreter/FunctionProvider.php
lib/Interpreter/Functions/Template/Html_To_Pdf.php

This PR removes the deprecated function `html_to_pdf`.
The required dependency to make this function work was too large to justify packaging with the app.
To continue using this function, you can install it separately via this app: https://github.com/Raudius/files_scripts_deprecated

Remove deprecated `html_to_pdf` function

---

lib/Event/RegisterScriptFunctionsEvent.php
lib/Interpreter/Functions/Nextcloud/Tag_File.php
lib/Interpreter/Functions/Nextcloud/TagsSerializerTrait.php
tests/integration/features/fixtures/test_nextcloud.lua

Fixes: https://github.com/Raudius/files_scripts/issues/134
This PR introduces the following changes:
- Allow `tag_file` to tag folder nodes as intended
- Small fix wrt function registration

Fix `tag_file` with folder input

---

CHANGELOG.md
appinfo/info.xml
package.json

- Removes deprecated function `html_to_pdf`, it may be installed separately by installing [files_scripts_deprecated](https://github.com/Raudius/files_scripts_deprecated).
- Integrates with new files API.
- Replaces single MIME-type restriction with multi-option file-type filtering, which works with extensions and MIME types.
- Replaces app-wide "show actions in menu" settings option, with per-script selection.

Release 4.0.0

---

lib/Interpreter/Functions/Nextcloud/ShareSerializerTrait.php

Issue:
The shares_find function in the Shares_Find class incorrectly assigns the shared_by value to the shared_with field. This error results in the function returning the user who created the share (shared_by) instead of the intended recipient (shared_with).
Fix:
This fix corrects the assignment within the serializeShare method of the Shares_Find class. The line 'shared_with' => $share->getSharedBy(), has been updated to 'shared_with' => $share->getSharedWith(),. This change ensures that the shared_with field accurately reflects the user with whom the file or folder is shared, aligning with the intended functionality of the method.
Impact:
This fix is crucial for any functionality relying on accurately determining the recipient of a shared resource. It ensures that scripts or features …

Fix Incorrect Assignment in Shares_Find Function

---

lib/Flow/Operation.php

fix: fixed retrieval of a node in a groupfolder by getById() when exe cuted on IRootFolder instead of user folder and multiple users with a mountpoint for the groupfolder are existing #119

Fix(GroupfolderFlow)

---

CHANGELOG.md
appinfo/info.xml
package.json

- Nextcloud 29 support
- Option to add inputs to occ actions (@ZeiTee)
- Button to duplicate a file action
- Retrieval of nodes inside group-folders for flow actions (@ZeiTee)
- Prevent creation of deleted nodes during flow action setup

Release 4.1.0

---

lib/Interpreter/Functions/Output/Log.php

Ensure `log`  function honors the loglevel submitted and if not matching any  level fallback to FATAL (4)
**Issue:**
* the `max(min($level, 0), 4);` always evaluates  to level 4 
```
{"reqId":"llSysqt5s7P2grK1DKUB","level":4,"time":"2024-08-23T22:04:42+00:00","remoteAddr":"","user":"--","app":"files_scripts","method":"","url":"--","message":"set_date_as_tag: info blubber","userAgent":"--","version":"29.0.5.1","data":{"app":"files_scripts"}}
{"reqId":"llSysqt5s7P2grK1DKUB","level":4,"time":"2024-08-23T22:04:42+00:00","remoteAddr":"","user":"--","app":"files_scripts","method":"","url":"--","message":"set_date_as_tag: warn blubber","userAgent":"--","version":"29.0.5.1","data":{"app":"files_scripts"}}
{"reqId":"llSysqt5s7P2grK1DKUB","level":4,"time":"2024-08-23T22:04:42+00:00","remoteAddr":"", …
```

Fix ensure log function honor submitted level
