composer.json
composer.lock
docs/Functions.md
lib/Interpreter/FunctionProvider.php
lib/Interpreter/Functions/Media/Ffmpeg.php
lib/Interpreter/Functions/Media/Ffprobe.php

Addresses: https://github.com/Raudius/files_scripts/issues/8
Adds support for basic media handling using FFmpeg.
Additions:
* `ffmpeg()` function to transform an input media file according to the given parameters
* `ffprobe()` function to retrieve metadata from a media file

Add FFmpeg functions for media handling

---

docs/Functions.md
lib/Interpreter/FunctionProvider.php
lib/Interpreter/Functions/Error/Abort.php
lib/Interpreter/Functions/Error/Log.php
lib/Service/ScriptService.php

* Make sure to correctly cast abort parameter to a string
* Move log to `Error` namespace
* Remove debug log from `ScriptService`
TODO:

Very minor fixes

---

bin/generate_docs.php
docs/Functions.md
lib/Interpreter/FunctionProvider.php
lib/Interpreter/Functions/Nextcloud/Tag_Create.php
lib/Interpreter/Functions/Nextcloud/Tag_File.php
lib/Interpreter/Functions/Nextcloud/Tag_File_Unassign.php
lib/Interpreter/Functions/Nextcloud/TagsCommand.php
lib/Interpreter/Functions/Nextcloud/Tags_Find.php

Addresses: https://github.com/Raudius/files_scripts/issues/15
Adds the functions: `tag_create`, `tag_file`, `tag_file_unassign`, `tags_find`

Add collaborative tagging functions

---

docs/Functions.md
lib/AppInfo/Application.php
lib/Interpreter/FunctionProvider.php
lib/Interpreter/Functions/Nextcloud/Tag_Create.php
lib/Interpreter/Functions/Nextcloud/Tag_File.php
lib/Interpreter/Functions/Nextcloud/Tag_File_Unassign.php
lib/Interpreter/Functions/Nextcloud/TagsSerializerTrait.php
lib/Interpreter/Functions/Nextcloud/Tags_Find.php
lib/Interpreter/Functions/Nextcloud/UserSerializerTrait.php
lib/Interpreter/Functions/Nextcloud/Users_Find.php
lib/Interpreter/RegistrableFunction.php
lib/Service/Notifier.php

Adds functions: `notify` and `users_find`

Add user and notification functions

---

CHANGELOG.md
appinfo/info.xml
package-lock.json
package.json

- Added function `file_copy_unsafe`
- Added function `file_move_unsafe`
- Added function `exists_unsafe`
- Added FFmpeg functions `ffmpeg`, `ffprobe`
- Added function `csv_to_table`
- Added tagging functions `tag_create`, `tag_file`, `tag_file_unassign`, `tags_find`
- Added function `shell_command`
- Added function `users_find` 
- Added function `notify`
- Removed unnecessary logging
- `root()` is deprecated in favour of `home()`
- `copy_file()` is deprecated in favour of `file_copy()`

Release 1.2.0

---

README.md

So people can copy and paste without issues

Add cd command to install instructions

---

lib/Interpreter/FunctionProvider.php
lib/Interpreter/Functions/Files/New_Folder.php

Addresses: https://github.com/Raudius/files_scripts/issues/38

Adds `new_folder` function to scripting API

---

src/components/ScriptSelect/ScriptInputComponent.vue
src/views/ScriptSelect.vue

* Filepick input
- Set default location to current directory when directories area allowed
- Set start browsing location to current directory
* Multiselect input
- Fix behaviour #56

Fix various script input issues

---

lib/Interpreter/Functions/Files/File_Copy.php
lib/Interpreter/Functions/Files/File_Copy_Unsafe.php
lib/Interpreter/Functions/Files/File_Move.php
lib/Interpreter/Functions/Files/File_Move_Unsafe.php

Allow folder as input in copy/move operations

Allow folders to be used in `file_copy` / `file_move`

---

lib/Interpreter/Functions/Files/Meta_Data.php

Strengthens exception handling in `meta_data` to prevent unhandled exceptions.
This addresses #58. Worth noting, however, that folders on mounted storages will always have a `local_path = nil`. This is due to how Nextcloud manages the file caching in  `\OC\Files\Storage\LocalTempFileTrait::toTmpFile`, which does not account for caching directories.

Fix meta_data for external storage folders

---

appinfo/routes.php
lib/Controller/ScriptController.php
lib/Db/Script.php
lib/Migration/Version020102Date20230309.php
lib/Service/PermissionService.php
src/api/script.ts
src/components/ScriptEdit.vue
src/store/scripts.ts
src/types/script.ts
src/views/Settings.vue

Resolves https://github.com/Raudius/files_scripts/issues/5

Allow actions to be limited to certain groups

---

src/components/ScriptEdit.vue
src/components/ScriptEdit/EditInputDetails.vue
src/components/ScriptSelect/ScriptInputComponent.vue
src/views/Flow.vue
src/views/ScriptSelect.vue

`NcMultiselect` is deprecated, usages replaced with newer `NcSelect`

Replace NcMultiselect with NcSelect component

---

lib/Interpreter/FunctionProvider.php
lib/Interpreter/Functions/Util/_Include.php
lib/Interpreter/RegistrableFunction.php

Adds ability to include external Lua files into the environment

Add `include` function to API

---

lib/Controller/ScriptController.php
lib/Db/Script.php
lib/Migration/Version030000Date20230324.php
src/components/ScriptEdit.vue
src/files.ts
src/store/scripts.ts
src/types/script.ts
src/views/ScriptSelect.vue

Limit actions by mimetype

---

src/components/ScriptSelect/ScriptInputComponent.vue

Resolves https://github.com/Raudius/files_scripts/issues/78

Fix checkbox input behaviour

---

lib/Interpreter/Functions/Input/Get_Input.php
src/components/ScriptEdit/EditInputDetails.vue
src/components/ScriptSelect/ScriptInputComponent.vue
src/types/script.ts

Resolves https://github.com/Raudius/files_scripts/issues/77

Expand input types

---

.gitignore
src/components/ScriptEdit/EditInputDetails.vue

String fix

---

bin/generate_docs.php
docs/Functions.md
lib/Controller/ScriptController.php
lib/Interpreter/Context.php
lib/Interpreter/FunctionProvider.php
lib/Interpreter/Functions/Output/Abort.php
lib/Interpreter/Functions/Output/Add_Message.php
lib/Interpreter/Functions/Output/Clear_Messages.php
lib/Interpreter/Functions/Output/Log.php
lib/Interpreter/Functions/Output/View_Files.php
src/views/ScriptSelect.vue
tests/integration/features/fixtures/test_messages_out.json
tests/unit/Interpreter/AbortTest.php
tests/unit/TestFunctionProvider.php

Adds the `view_files` function, which allows to set files for viewing after execution.

Add `view_files` function

---

lib/Migration/Version030100Date20231215.php

Fixes: https://github.com/Raudius/files_scripts/issues/117

Add default value to `filescript_inputs`.`options` column

---

lib/Event/RegisterScriptFunctionsEvent.php
lib/Interpreter/Functions/Nextcloud/Tag_File.php
lib/Interpreter/Functions/Nextcloud/TagsSerializerTrait.php
tests/integration/features/fixtures/test_nextcloud.lua

[stable27] Fix `tag_file` for folders

---

lib/AppInfo/Application.php
lib/Controller/ScriptController.php
lib/Controller/SettingsController.php
lib/Db/Script.php
lib/Listener/LoadAdditionalListener.php
lib/Listener/ShareLinkAccessedListener.php
lib/Migration/Version040000Date20231217.php
lib/Settings/AdminSettings.php
src/components/ScriptEdit.vue
src/store/scripts.ts
src/types/script.ts
src/views/ScriptSelect.vue
src/views/Settings.vue
tests/integration/features/bootstrap/FeatureContext.php

Implements: https://github.com/Raudius/files_scripts/issues/102
Replace old app-global settings option `action_in_menu` with a per-script option `showInContext`

Allow selection of menu option per script

---

lib/Controller/ScriptController.php
src/files.ts
src/types/files.ts
src/types/script.ts

Fixes: https://github.com/Raudius/files_scripts/issues/143

Fix script selection modal not working when scripts have mimetype restrictions

---

CHANGELOG.md
appinfo/info.xml
package.json

- Fixed issue where selection modal would not work when scripts have mimetype restrictions.

Release 4.0.1

---

lib/Controller/ScriptController.php

Fixes: https://github.com/Raudius/files_scripts/issues/143

Fix bug where scripts would not work in files outside home directory

---

CHANGELOG.md
appinfo/info.xml
package.json

- Fixed a bug where scripts could not be run on files outside the home directory.
- Improved grammar and typos in documentation and app strings.

Release 4.0.2

---

src/files.ts

Fixes https://github.com/Raudius/files_scripts/issues/143#issuecomment-1872540158

Fix file action execution handling

---

lib/Interpreter/Functions/Nextcloud/Tags_Find.php

Fixes: https://github.com/Raudius/files_scripts/issues/150

Fix tags_find error and parameter handling

---

lib/Interpreter/Functions/Nextcloud/Tags_Find.php

Backport of https://github.com/Raudius/files_scripts/pull/151

[stable27] Fix tags_find error and parameter handling

---

lib/Interpreter/Functions/Util/Http_Request.php

Update Http_Request.php PUT method typo

---

lib/Command/RunScript.php

Added the possibility to pass input files to actions executed using occ command

Added occ file input

---

lib/Flow/Operation.php

Fixes https://github.com/Raudius/files_scripts/issues/161
* Refactor node creation in flow setup
* Set deleted node path to `old_node_path` instead of trying to create file node for the input files

Fix flow operation setup

---

src/components/ScriptCard.vue
src/store/scripts.ts
src/views/Settings.vue

Addresses: https://github.com/Raudius/files_scripts/issues/166
Provides action button to duplicate a script in the front-end

Allow duplication of scripts
